#!/usr/bin/env node

var main = require("./lib/monitor");
var program = require("commander");
var fs = require("fs");

program
.command("monitor <uri> [")
.description("Monitor the Operating System main values and report them to the Dashboard")
.option("-c, --config-file <configfile>", "Path to json file with configuration")
.action(function(uri, opts) {

	fs.readFile(opts.configFile, function(err, file) {
		var options = JSON.parse(file);
		main(uri, options);
	})
});

program.parse(process.argv);

